# Pre-commit hooks for code quality
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        # Use pyproject.toml for ruff configuration

# Temporarily disabled mypy until httpx typing issues are resolved
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.17.1
#   hooks:
#     - id: mypy
#       # Use pyproject.toml for mypy configuration
#       files: ^src/
#       args: [--config-file=pyproject.toml]
#       additional_dependencies: [types-docker, types-requests, numpy, structlog]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'PYTHONPATH=${PWD}/src:$PYTHONPATH python -m pytest tests/test_retry_manager.py tests/test_session_recovery.py tests/test_circuit_breaker.py tests/test_enhanced_client.py -x --tb=short'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
